version: 2.1
executors:
  default:
    working_directory: ~/go/src/github.com/mattermost/mmetl
    docker:
      - image: circleci/golang:1.13

jobs:
  lint:
    executor:
      name: default
    steps:
      - checkout
      - run:
          command: |
            echo "Installing mattermost-govet."
            GO111MODULE=off go get -u github.com/mattermost/mattermost-govet
            echo "Installing shadow"
            GO111MODULE=off go get -u golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow
            make check-style

  test:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/go/src/github.com/mattermost/mmetl
    environment:
      COMPOSE_PROJECT_NAME: "circleci"
    steps:
      - checkout
      - attach_workspace:
          at: ~/go/src/github.com/mattermost/
      - run:
          name: Run Tests
          command: |
            make test

  build:
    executor:
      name: default
    steps:
      - checkout
      - run: make package
      - persist_to_workspace:
          root: .
          paths:
            - ./build/*.tar.gz
            - ./build/*.zip

  publish-github-release:
    docker:
      - image: cibuilds/github:0.12
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./build/*.tar.gz
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./build/*.zip

workflows:
  version: 2
  untagged-build:
    jobs:
      - lint
      - test
  tagged-build:
    jobs:
      - lint:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - test:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build:
          requires:
            - lint
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish-github-release:
          context: matterbuild-github-token
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
